<script setup>
const query=ref(''), selected=ref('hpml-view-for-user')
const tasks=['hpml-view-for-user','hermes-joint-workspace','jev-integration','mcp-workspace','mow-mot-moit-mout','vps-clean-20-9-26']
const filtered=computed(()=>tasks.filter(t=>t.includes(query.value.toLowerCase())))
const draft=computed(()=>selected.value==='hpml-view-for-user')
const tabs=[{label:'Kiểm soát',slot:'control'},{label:'Nội dung công việc',slot:'content'}]
const items=[{label:'Mục tiêu',slot:'goal',defaultOpen:true},{label:'Tiến độ',slot:'progress'},{label:'Tình trạng',slot:'activity',defaultOpen:true}]
const stageNames=['Tạo việc · Thống nhất mục tiêu','Thống nhất kế hoạch','Triển khai','Nghiệm thu theo mục tiêu']
const states={pending:'Chưa làm',done:'Đã xong',blocked:'Đang tắc',changing:'Đang điều chỉnh',unknown:'Chưa có dữ liệu'}
const stages=computed(()=>stageNames.map((label,i)=>({label,state:draft.value?['done','changing','pending','pending'][i]:'unknown'})))
const team=[{id:'gpt-chat',label:'Chat GPT'},{id:'gpt-work',label:'Codex / GPT Work'},{id:'claude-chat',label:'Chat Claude'},{id:'claude-work',label:'Claude Code CLI / Cowork'},{id:'hermes-chat',label:'Hermes Chat'},{id:'hermes-code',label:'Hermes Code'}]
// UI fixture only. Replace the whole snapshot on a newer source revision; never accumulate dots.
const snapshot=computed(()=>({lastActors:draft.value?['gpt-work']:[],activeActors:[]}))
const documents={'mow-mot-moit-mout':'/ui-preview/hpml-view-for-user/documents/mow-mot-moit-mout.html'}
const documentUrl=computed(()=>documents[selected.value])
const dotLabel=(actor,column)=>`${actor.label} · ${column==='lastActors'?'Vừa làm':'Đang làm'}: ${snapshot.value[column].includes(actor.id)?'Có tín hiệu trong mẫu UI':'Chưa có tín hiệu'}`
</script>
<template>
<div class="min-h-screen bg-white text-slate-900"><div class="px-6 py-3 max-w-[1600px] mx-auto">
<header class="flex justify-between items-center mb-3 gap-3"><h1 class="text-lg font-semibold">Task html view</h1><UBadge color="gray" variant="soft" size="xs">Mẫu UI · Chưa nối trạng thái GitHub</UBadge></header>
<div class="task-layout grid grid-cols-1 gap-6 items-start">
<aside class="min-w-0 lg:sticky lg:top-3"><UInput v-model="query" placeholder="Tìm công việc…" aria-label="Tìm công việc" size="sm"/><div class="flex justify-between mt-3 mb-1 text-xs text-slate-500"><h2 class="font-semibold">Công việc</h2><span>{{filtered.length}}</span></div>
<nav aria-label="Danh sách công việc" class="space-y-0.5"><UButton v-for="task in filtered" :key="task" :color="selected===task?'primary':'gray'" :variant="selected===task?'soft':'ghost'" block :ui="{base:'justify-start text-left'}" class="px-2.5 py-2 !justify-start" size="sm" @click="selected=task"><span class="min-w-0"><span class="block break-words font-medium">{{task}}</span><span class="block mt-0.5 text-[11px] font-normal text-slate-500">{{task==='hpml-view-for-user'?'Đang chỉnh giao diện':task==='mow-mot-moit-mout'?'Có HTML công việc':'Chưa nối trạng thái'}}</span></span></UButton><p v-if="!filtered.length" class="p-2 text-sm text-slate-500">Không có công việc khớp tên.</p></nav></aside>
<main class="min-w-0"><h2 class="text-base font-semibold break-words mb-2">{{selected}}</h2>
<UTabs :items="tabs" :ui="{wrapper:'relative space-y-3',list:{height:'h-9',tab:{height:'h-7',size:'text-sm'}}}">
<template #control><UAccordion :key="selected" :items="items" multiple :ui="{wrapper:'flex flex-col w-full gap-2',container:'border border-slate-200 rounded-lg overflow-hidden',item:{padding:'px-3 pb-3 pt-0',color:'text-slate-700'}}">
<template #default="{item,open}"><div class="flex items-center gap-3 px-3 py-2 bg-slate-50/60"><UButton color="gray" variant="ghost" class="!p-0 hover:!bg-transparent" :class="item.slot!=='progress'?'flex-1':''" :ui="{base:'justify-between text-left'}"><span class="text-sm font-semibold text-slate-900">{{item.label}}</span><span class="ml-2 text-slate-400" aria-hidden="true">{{open?'−':'+'}}</span></UButton><div v-if="item.slot==='progress'" class="flex-1 grid grid-cols-4 gap-1.5" aria-label="Bốn giai đoạn công việc"><UTooltip v-for="(stage,i) in stages" :key="stage.label" :text="`${i+1}. ${stage.label} — ${states[stage.state]}`" class="w-full"><button type="button" class="stage-hit w-full" :title="`${i+1}. ${stage.label} — ${states[stage.state]}`" :aria-label="`${i+1}. ${stage.label} — ${states[stage.state]}`"><span class="stage-bar" :class="`state-${stage.state}`"/></button></UTooltip></div></div></template>
<template #goal><template v-if="draft"><p class="text-sm leading-5">View dễ nhìn để biết mục tiêu, biết trạng thái, giúp User điều hành hiệu quả.</p><p class="mt-1 text-sm">Lắp ráp tối đa, hạn chế code mới tối đa.</p></template><p v-else class="text-sm text-slate-500">Chưa nạp mục tiêu từ nguồn GitHub.</p></template>
<template #progress><ol class="space-y-1 text-xs"><li v-for="(stage,i) in stages" :key="stage.label" class="flex justify-between gap-3"><span>{{i+1}}. {{stage.label}}</span><span class="text-slate-500">{{states[stage.state]}}</span></li></ol><p class="mt-2 text-[11px] text-slate-500">Xám: chưa làm · Xanh: đã xong · Đỏ: đang tắc · Vàng cam: điều chỉnh. Màu đang minh họa bố cục.</p></template>
<template #activity><table class="w-full text-sm" aria-label="Tình trạng sáu thành viên"><thead><tr class="text-xs text-slate-500 border-b border-slate-100"><th class="text-left font-normal pb-1.5">Thành viên</th><th class="font-normal pb-1.5 w-20">Vừa làm</th><th class="font-normal pb-1.5 w-20">Đang làm</th></tr></thead><tbody><tr v-for="actor in team" :key="actor.id" class="border-b last:border-0 border-slate-100"><th scope="row" class="text-left font-normal py-1.5">{{actor.label}}</th><td v-for="column in ['lastActors','activeActors']" :key="column" class="text-center py-1.5"><span class="status-dot" :class="{active:snapshot[column].includes(actor.id)}" role="img" :aria-label="dotLabel(actor,column)" :title="dotLabel(actor,column)" tabindex="0"/></td></tr></tbody></table><p class="text-[11px] text-slate-500 mt-2">Chấm xanh: có tín hiệu · Chấm xám: chưa có tín hiệu. Đây là mẫu UI.</p></template>
</UAccordion><details class="mt-3 text-xs text-slate-500"><summary class="cursor-pointer">Ghi chú đấu nối dữ liệu</summary><div class="mt-2 space-y-2 leading-5"><p>GitHub là nguồn chuẩn. Webhook báo có bản mới; VPS lấy HTML và trạng thái của cùng một phiên bản, rồi thay toàn bộ bản hiển thị.</p><p>Tiến độ: 4 giai đoạn, mỗi giai đoạn có trạng thái và ghi chú. Tình trạng: người vừa làm, người đang làm, thời điểm nhận, phiên bản nguồn. Bản mới thay bản cũ, không cộng dồn chấm xanh.</p><p>Không có tín hiệu đang làm thì để xám; không suy ra từ người push. Chỉ áp dụng bản mới của đúng công việc. Cơ chế đồng bộ chưa bật.</p></div></details></template>
<template #content><template v-if="documentUrl"><div class="flex justify-between items-center gap-3 text-xs text-slate-500 mb-2"><span>HTML nguyên bản từ GitHub · Bản đã lấy về</span><UButton :to="documentUrl" target="_blank" color="gray" variant="ghost" size="xs">Mở rộng ↗</UButton></div><iframe :key="documentUrl" :src="documentUrl" :title="`Nội dung ${selected}`" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" class="document-frame w-full border border-slate-200 rounded-lg bg-white"/></template><UAlert v-else color="gray" title="Chưa có HTML nội dung được nối vào" description="Tab này dành trọn cột phải cho trang HTML của công việc. Chọn mow-mot-moit-mout để xem HTML hiện có trên GitHub."/></template>
</UTabs></main></div></div></div>
</template>
<style>
/* Existing Knowledge track x 1.5, reduced by 20% = x 1.2. */
@media(min-width:1024px){.task-layout{grid-template-columns:calc((100% - 72px)/4 * 1.2) minmax(0,1fr)}}
.stage-hit{display:flex;align-items:center;min-height:24px;border-radius:6px}.stage-hit:focus-visible,.status-dot:focus-visible{outline:2px solid #007aff;outline-offset:3px}.stage-bar{display:block;width:100%;height:6px;border-radius:999px;background:#e5e5ea}.state-done{background:#34c759}.state-blocked{background:#ff3b30}.state-changing{background:#ff9f0a}.status-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:#e5e5ea;vertical-align:middle}.status-dot.active{background:#34c759}.document-frame{height:calc(100dvh - 230px);min-height:520px}
</style>
